apiVersion: apps/v1
kind: Deployment
metadata:
  #Es importante mantener mismo nombre que el docker-compose
  name: postgres14
spec:
  replicas: 1
  selector:
    matchLabels:
      role: postgres
  template:
    metadata:
      labels:
        role: postgres
    spec:
      containers:
        - name: postgres14
          image: postgres:14-alpine
          ports:
            - containerPort: 5432
          env:
            #Se obtienen los valores por configmap
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: database
          #En volumeMounts se utiliza el volumen definido
          volumeMounts:
            - name: data-postgres
              mountPath: /var/lib/postgresql/data
      #definicion de volumen
      volumes:
        - name: data-postgres
          #hostPath:
            #path: /var/lib/postgresql/data
            #type: DirectoryOrCreate
          persistentVolumeClaim:
            claimName: postgres-pvc